# Digital Ocean App Platform - Static Site Config
# Deploy to racheloalden.com
# Docs: https://docs.digitalocean.com/products/app-platform/

name: racheloalden
region: nyc

static_sites:
  - name: portfolio
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /
    # Connect your GitHub repo in the Digital Ocean dashboard
    # or uncomment and set your repo:
    # github:
    #   repo: your-username/racheloalden
    #   branch: main
    #   deploy_on_push: true
